steps:
  - name: gcr.io/cloud-builders/docker
    id: build-api
    waitFor: ['-']
    args:
      - build
      - -f
      - apps/api/Dockerfile
      - --cache-from
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/api:latest
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/api:${_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/api:latest
      - .

  - name: gcr.io/cloud-builders/docker
    id: build-web
    waitFor: ['-']
    args:
      - build
      - -f
      - apps/web/Dockerfile
      - --build-arg
      - NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}
      - --build-arg
      - NEXT_PUBLIC_DONATE_GITHUB_URL=${_NEXT_PUBLIC_DONATE_GITHUB_URL}
      - --build-arg
      - NEXT_PUBLIC_DONATE_CRYPTO_ADDRESS=${_NEXT_PUBLIC_DONATE_CRYPTO_ADDRESS}
      - --build-arg
      - NEXT_PUBLIC_DONATE_CRYPTO_LABEL=${_NEXT_PUBLIC_DONATE_CRYPTO_LABEL}
      - --build-arg
      - NEXT_PUBLIC_DONATE_KOFI_URL=${_NEXT_PUBLIC_DONATE_KOFI_URL}
      - --build-arg
      - NEXT_PUBLIC_CONTACT_NAME=${_NEXT_PUBLIC_CONTACT_NAME}
      - --build-arg
      - NEXT_PUBLIC_CONTACT_WHATSAPP=${_NEXT_PUBLIC_CONTACT_WHATSAPP}
      - --cache-from
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/web:latest
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/web:${_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/web:latest
      - .

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/api:${_TAG}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/api:latest
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/web:${_TAG}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/web:latest

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
